name: sam-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::pytorch-cuda=12.1
  - opencv
  - numpy
  - ipykernel
  - jupyterlab
  - pip
  - pip:
    - opencv-python
    - segment-anything
